name: Terraform CI Validity check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0 

    - name: Terraform Init
      working-directory: module
      run: terraform init

    - name: Terraform Format
      working-directory: module
      run: terraform fmt -check

    - name: Terraform Validate
      working-directory: module
      run: terraform validate

    - name: Terraform Plan
      working-directory: module
      run: terraform plan

    - name: Upload Plan Artifacts
      if: success() && github.event_name == 'push'
      working-directory: module
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: planfile

    - name: Notify on Failure
      if: failure()
      run: echo "Terraform checks failed!"
