apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplication
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: ronnahmany/testrun:latest
        ports:
        - containerPort: 80
