name: Build and Deploy Helm Chart

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Helm Chart
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Helm tool installer
      uses: Azure/setup-helm@v4.2.0

    - name: Package Helm Chart
      run: |
        helm package ./kub --destination ./charts

    - name: Upload Helm Chart Artifact
      uses: actions/upload-artifact@v3
      with:
        name: helm-chart
        path: 'charts/*.tgz'

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Helm tool installer
      uses: Azure/setup-helm@v4.2.0

    - name: Configure kubectl for EKS
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    - name: Download Helm Chart Artifact
      uses: actions/download-artifact@v3
      with:
        name: helm-chart

    - name: Install/Upgrade Helm Chart
      run: helm upgrade --install my-release ./charts/my-chart-*.tgz --namespace default --create-namespace
